"""adding a downloads column

Revision ID: 2a353e7f312d
Revises: 600f198c686b
Create Date: 2023-12-14 16:59:34.673847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a353e7f312d'
down_revision = '600f198c686b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downloads', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vases', schema=None) as batch_op:
        batch_op.drop_column('downloads')

    # ### end Alembic commands ###
