"""added indexing to public on vases actually

Revision ID: 600f198c686b
Revises: 8d9844a788c6
Create Date: 2023-06-26 09:05:49.556411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600f198c686b'
down_revision = '8d9844a788c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vases_public'), ['public'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vases_public'))

    # ### end Alembic commands ###
