"""unique names for vases w user id concated

Revision ID: 8d9844a788c6
Revises: a0e4e6ded56d
Create Date: 2023-06-26 07:49:55.400337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9844a788c6'
down_revision = 'a0e4e6ded56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_name', sa.Text(), nullable=True))
        batch_op.drop_index('ix_vases_name')
        batch_op.create_index(batch_op.f('ix_vases_unique_name'), ['unique_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vases_unique_name'))
        batch_op.create_index('ix_vases_name', ['name'], unique=False)
        batch_op.drop_column('unique_name')

    # ### end Alembic commands ###
