"""added public vases and admin columns

Revision ID: a0e4e6ded56d
Revises: 1c09f5a6bee4
Create Date: 2023-06-25 16:12:02.457650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e4e6ded56d'
down_revision = '1c09f5a6bee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Integer(), nullable=True))

    with op.batch_alter_table('vases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vases', schema=None) as batch_op:
        batch_op.drop_column('public')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
